server:
  servlet:
    context-path: "/api"
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lxqtpr2021
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update

security:
  jwt:
    accessSecret: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
    refreshSecret: "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="
    accessExpirationInMinutes: 5
    refreshExpirationInMinutes: 43200

org:
  jobrunr:
    job-scheduler:
      enabled: true
    dashboard:
      enabled: true
    background-job-server:
      enabled: true
